### ISSUE TITLE
Check if enzyme mounts components on the DOM by default

### ISSUE THREAD

**Issue by ramonrf** [ramonrf/react-template#5]
I have noticed that in Risk Averter project components are not mounted by default on the DOM, DOM seems to be empty with only a modal. Need to test this on a toy project to make sure what is the default behavior

**Comment by rareyesdev** [comment]
No, Enzyme only mounts to the DOM when using `attachTo` while mounting. See http://airbnb.io/enzyme/docs/api/ReactWrapper/detach.html
